image: node:latest

stages:
  - build
  - test
  - image

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    - . ~/.nvm/nvm.sh
    - nvm install node
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test

create_image:
  stage: image
  script:
    - $HOME/../packer.io build packer.json
