image: node:latest

stages:
  - build
  - test
  - image

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test

create_image:
  stage: image
  script:
    - who
    - pwd
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
    - aws
    - export PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
    - $HOME/../packer.io build packer.json
