image: node:latest

stages:
  - build
  - test
  - image

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test

create_image:
  stage: image
  script:
    - export PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
    - $HOME/../packer.io build packer.json
