image: node:latest

stages:
#  - build
#  - test
  - deploy

#before_script:
#  - pwd
#  - ./packer.io --version
#
#cache:
#  paths:
#    - node_modules/

#install_dependencies:
#  stage: build
#  script:
#    -
#    - npm install ./NodeHelloWorld
#  artifacts:
#    paths:
#      - node_modules/
#
#testing_testing:
#  stage: test
#  script: npm test

deploy_linux:
  stage: deploy
  script:
    - $HOME/../packer.io build -var profile=default packer.json
